### ISSUE TITLE
No OpenOCD (dead links)

### ISSUE THREAD

**Issue by moritzstoetter** [microsoft/vcpkg-ce-catalog#52]
All links related to `openocd` are dead. They all point to non-existent addresses beginning with "https://github.com/microsoft/openocd/...."  (see https://github.com/microsoft/vcpkg-ce-catalog/blob/main/tools/microsoft/openocd-0.12.0.json).

**Comment by moritzstoetter** [comment]
Tagging @benmcmorran, since he's explicitly mentioned in associated file

**Comment by benmcmorran** [comment]
Sorry, I'm no longer on this team, but @itodirel may be able to provide more information.

**Comment by BillyONeal** [comment]
Given https://github.com/microsoft/vcpkg-ce-catalog/pull/51 I assume OpenOCD being removed was by design.
